### ISSUE TITLE
Feature: Add full message content support

### ISSUE THREAD

**Issue by TisRyno** [gauthier-th/embed-visualizer#1]
Hey, just found this library and I'm ridiculously happy it exists as I haven't found anything else other than the original library this is based off of.

Just wondering if you'd consider adding support for the full avatar, name, message content as well as just the embed?

Alternatively can you just expose the Markdown parsing so it can be used to parse any message?

**Comment by gauthier-th** [comment]
Hey, glad this could help you ;)

Yes, I will expose the Markdown parsing in a few hours, i'll see later for implement complete message parsing.
(you can also make a pull request if you want)

**Comment by TisRyno** [comment]
Pulled the latest release, works perfectly for me now.
Thanks for responding so quick, if I ever finish the thing I'm trying to do I'll add a PR for the full message support
