### ISSUE TITLE
parseContent doesn't seem to append to new line.

### ISSUE THREAD

**Issue by NTMNathan** [gauthier-th/embed-visualizer#3]
I'm making an embed builder website and when I try to use `parseContent` or `parseTitle`, it doesn't seem to go to a new line.

Also markdown isn't properly supported? Could this be a css issue i'm having or not?

![](https://i.imgur.com/2Wdtumu.png)

**Comment by Kaisarion** [comment]
Can repro

**Comment by gauthier-th** [comment]
When I create an embed from the `example` folder code with your message content, new lines are displaying right, so this is probably a problem with your css.

You should apply this to your embed container:
```css
white-space: pre;
```
