### ISSUE TITLE
TypeError: onError is not a function

### ISSUE THREAD

**Issue by popop098** [gauthier-th/embed-visualizer#6]
thank you for fix code design issue.
look this image
![image](https://user-images.githubusercontent.com/53284350/178922913-f8c48d7a-94da-4fd5-9546-a7b451a3bb20.png)
I got this error when embed description empty.
correct this error to avoid errors when the embed description value is empty.

**Comment by gauthier-th** [comment]
An embed description should not be empty.
I fixed the error throwing in v1.3.2. Now the error message should be more clear.

![image](https://user-images.githubusercontent.com/37781713/178975205-6c5cd0b0-2943-4e20-a8e3-3f922c1a8d2d.png)
